version: '3.8'

services:
  # База данных PostgreSQL
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: bullockz
      POSTGRES_PASSWORD: mostbestofthebest
      POSTGRES_DB: library_api_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pir_docker_network

  # Интерфейс управления базой данных (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - pir_docker_network

  # Laravel-приложение (PHP + FPM)
  app:
    build:
      context: .  # Указывает, что использовать локальный Dockerfile
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www  # Монтируем код внутрь контейнера
    depends_on:
      - db
    networks:
      - pir_docker_network

  # Nginx - веб-сервер, который отдаёт Laravel
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Подключаем конфиг Nginx
      - .:/var/www
    depends_on:
      - app
    networks:
      - pir_docker_network

volumes:
  pgdata:

networks:
  pir_docker_network:
    driver: bridge
